name = "insurance-kb-api"
main = "src/index.ts"
compatibility_date = "2024-10-18"

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "KV"
id = "d57f70351eb94f7c8b13d338f0f811ad"

[vars]
CORS_ORIGIN = "https://insurance-kb.cooperation.tw"
